#!/bin/bash
if [[ $# -lt 1 ]]; then
    echo 'usage: apputil {start|stop|ps}'
fi

app_dir=`dirname $0`
cd $app_dir

if [[ $1 = "start" ]]
then
    php bootstrap.php &
elif [[ $1 = "stop" ]]
then
    if [ -f './.pid' ]
    then
        kill `cat ./.pid`
    else
        echo -e "\e[0;31m"
        echo "no any running process found!"
        echo -e "\e[0m"
    fi
elif [[ $1 = "ps" ]]
then
    if [ -f './.pid' ]
    then
        echo -e "\e[0;32m"
        ps -o pid,ppid,sess,tt,user,start_time,time,stat,%cpu,rss,vsz,size,%mem,cmd --pid `cat .pid` --ppid `cat .pid`
        echo -e "\e[0m"
    else
        echo -e "\e[0;31m"
        echo "no any running process found!"
        echo -e "\e[0m"
    fi
fi
