CREATE TABLE IF NOT EXISTS `t_conf` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `k` VARCHAR(255) NOT NULL COMMENT '配置键',
    `v` VARCHAR(255) NOT NULL COMMENT '配置值',
    `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY idx_k(`k`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
